const crypto = require('crypto')

const INITIAL_EMAILS = [
  '0626054767s@gmail.com','23136014@nwu.ac.za','2giddi@gmail.com','316vdm@gmail.com',
  '67smit@gmail.com','69pikkie@gmail.com','AMeyer1952@gmail.com','Alettam.ludick@gmail.com',
  'Amanda.duPlooy@outlook.com','Anneliekruger01@gmail.com','Anzuette.goosen@gmail.com',
  'CHALL3582@GMAIL.COM','CHANTELPHILLIPSON@GMAIL.COM','Carina.kalp@eskom.co.za',
  'Carmen.visser.01@gmail.com','Christie.eksteen@gmail.com','Cries@mpact.co.za',
  'Elizabethlabusch72@gmail.com','Elizenortje3@gmail.com','ElnaC.Private@gmail.com',
  'Ericadestadler1@gmail.com','Hanlie.brink@rocketmail.com','Hardusdk@outlook.com',
  'Hermienb1234@gmail.com','Jacoschlebusch2@gmail.com','Karien@tricho.co.za',
  'Lamot@live.co.za','Leerindamuller@gmail.com','Liezlieb@gmail.com',
  'Lizellehairbeauty@gmail.com','Maanzzandberg@gmail.com','Prinsloo2.amp@gmail.com',
  'Riettefourie3@gmail.com','Sashaduplessis95@gmail.com','Smostert9@gmail.com',
  'Sonnenbergmining@gmail.com','Stefanie.Swart@gmail.com','Stephanieolivier1969@gmail.com',
  'Surette@live.co.uk','Ulise.cilliers@gmail.com','a3vvmails@gmail.com',
  'abrie@djcon.co.za','absotony@gmail.com','acmaritz57@gmail.com',
  'adele.potgieter75@gmail.com','adelebecker78@gmail.com','adewet@multipol.co.za',
  'admin@climagen.co.za','admin@krielfarm.co.za','admin@montspa.co.za',
  'adrivonm@gmail.com','adv.9876@gmail.com','affieplaasselfsorg@gmail.com',
  'akoegie@yahoo.com','aletjonker123@gmail.com','alida.jacobs9@gmail.com',
  'alidadv26@gmail.com','alidawiesner@gmail.com','alisha.bronkhorst@gmail.com',
  'aljec.ec@gmail.com','aljolena12367@gmail.com','alombaard.al@gmail.com',
  'alta.mnel@gmail.com','altaedmeyer@gmail.com','amadreyer81@gmail.com',
  'amandafleischer02@gmail.com','amandaleroux5@gmail.com','amandarasmusvorster@gmail.com',
  'amandaschlebusch2@gmail.com','amandasebastian3@gmail.com','amaree@sandveld.net',
  'amelia.nel051@gmail.com','ameliab@absamail.co.za','ancerina@gmail.com',
  'andre.grobler@live.co.za','andrewbosman401@gmail.com','andrewclaassen@live.com',
  'andriesvheyde@gmail.com','anelisegr@gmail.com','aneradley9@gmail.com',
  'anette.basson@icloud.com','angel19870527@gmail.com','angeliquedebruyn@gmail.com',
  'anitahopley2@gmail.com','anitaniets@gmail.com','anitasmit696@gmail.com',
  'annabezuidenhout13@gmail.com','annadurandt083@gmail.com','annalene57@gmail.com',
  'annaliene@gmail.com','annaliseve@icloud.com','annamare540@gmail.com',
  'annapiranna007@gmail.com','annatjie.blackhall@gmail.com','annatjiebuys@gmail.com',
  'anneke8508@gmail.com','annelene1111@gmail.com','annelinenel@vodamail.co.za',
  'annerinep@gmail.com','annette.greve@gmail.com','annettejacobs87@gmail.com',
  'anniesaimlife@gmail.com','annson926@gmail.com','anrib3069@gmail.com',
  'ansabadenhorst@gmail.com','ansbotha@gmail.com','ansie.solomon@lantic.net',
  'ansie@actionsure.co.za','ansieburger11@gmail.com','ansieroos3@gmail.com',
  'ansomelombaard@gmail.com','antjiemj@gmail.com','antoinette@paulv.co.za',
  'antonb@bstdata.co.za','anzawg@gmail.com','arinava@lantic.net',
  'askerikagreen@gmail.com','avermeulen048@gmail.com','aviljoen17@gmail.com',
  'backtobasicstutorcentre@gmail.com','badenhorsta205@gmail.com','bakkiesdp@gmail.com',
  'bauermeisterbridget16@gmail.com','bcschutte42@gmail.com','bekkerdirk@gmail.com',
  'belinda.venter21@gmail.com','belindataljaard30@gmail.com','benade.johannes@yahoo.com',
  'berenicegkock@gmail.com','bernicproperties@gmail.com','berniehenning9@gmail.com',
  'bertholdottomeyer@gmail.com','besterrc@gmail.com','bettie.vdw92@gmail.com',
  'bettievdberg@yahoo.com','beukeslm77@gmail.com','bezuidenhoudta@gmail.com',
  'biancabarnard6@gmail.com','bisschoff5@icloud.com','bisschoff@icloud.com',
  'bizzbuss1994@gmail.com','bluecrane01@gmail.com','bluffpet@gmail.com',
  'blyde2009@gmail.com','bonthuysrene@gmail.com','boonzaaierrohanel@gmail.com',
  'boshoffjaco7@gmail.com','bothamarlese@gmail.com','boutertjiemyrna@gmail.com',
  'brieljenethy@gmail.com','bringarde.nieman@gmail.com','britzbd@gmail.com',
  'brownmari007@gmail.com','c.debruyn1234@gmail.com','car2carct@gmail.com',
  'carikeot@gmail.com','carlwernich@gmail.com','caro.d.j@hotmail.com',
  'carolinehepburn@hotmail.com','carstens.hanel@gmail.com','cat.vandijken@gmail.co.za',
  'cat.vandijken@gmail.com','cathy@multiprojects.com','ccbas70@gmail.com',
  'cecile.botha1@gmail.com','cecilematthee@gmail.com','cecilestrong@gmail.com',
  'celestevandenberg7@gmail.com','celestewillard777@gmail.com','ceroldinem@gmail.com',
  'cfbern1977@gmail.com','chantalrobson@jbleroux.co.za','chantel.jonker7@gmail.com',
  'chantellemaree7@gmail.com','chardinealshama@gmail.com','charlenevanj@gmail.com',
  'charleslotter@rocketmail.com','charletsmit15@gmail.com','charlwewege@gmail.com',
  'charmainepartyplanner@gmail.com','charnelle.visser@gmail.com','chinelvanwyk91@gmail.com',
  'chriselda@lomtrans.co.za','chrisleadejager@gmail.com','christamari.harmse@gmail.com',
  'christelene01@gmail.com','chrizelda6478@gmail.com','cindyblom.blom@gmail.com',
  'cins512@icloud.com','claytonnette322@gmail.com','cloetebabsie@gmail.com',
  'cloetejs1978@gmail.com','cloetemelanie03@gmail.com','clventer691@gmail.com',
  'cmvzyl@gmail.com','cobikleynhans@gmail.com','colette.schoeman@gmail.com',
  'colettemuller1@gmail.com','comfibreeze@gmail.com','conradiec4@gmail.com',
  'corette.glasfit@gmail.com','corlia.adams@gmail.com','corliavndk@gmail.com',
  'corliens@gmail.com','corna1966@gmail.com','corne.vanheerden01@gmail.com',
  'cornellekriel@gmail.com','corriemyburgh70@gmail.com','cplnfrancis@gmail.com',
  'craig@wmgs.co.za','creativehands61@gmail.com','crowther@humming-bird.co.za',
  'cura.lesotho@gmail.com','cynthiamathys8@gmail.com','dalenejventer@gmail.com',
  'danabayroofing@gmail.com','dave@dlsjhb.co.za','david.eduard.n@gmail.com',
  'davideden533@gmail.com','dawid@dafstersoft.co.za','debbiecbezuidenhout@gmail.com',
  'debbiestolsie@gmail.com','debeerannatjie6@gmail.com','dekockmarchell21@gmail.com',
  'dellie.vandeventer@gmail.com','delmarieferreira@yahoo.com','denine.parsons@rfg.com',
  'denise15ogrady@outlook.com','deniseerasmus@yahoo.com','denslin96@gmail.com',
  'denysschene@yahoo.com','des.jvrensburg@gmail.com','devilliersjunica@yahoo.co.uk',
  'dewald.h.scheepers@gmail.com','dianawessels7@gmail.com','diedreswart@hotmail.com',
  'diefourietjies@gmail.com','dienkie@triple3.co.za','dlnopperman@gmail.com',
  'doratheabester68@gmail.com','doreenhenning@gmail.com','dorettedk@gmail.com',
  'dorothea@bcwines.co.za','douwswanepoel@gmail.com','dpennekan@gmail.com',
  'dreyerlourens@gmail.com','driekiedp1@gmail.com','driesrossouw6@gmail.com',
  'dthomass100@gmail.com','duanjansen6@gmail.com','duplessisera@yahoo.co.nz',
  'dupreezpetro3@gmail.com','ebersohn.christelle@yahoo.com','ecordy77@gmail.com',
  'eduplooy28@gmail.com','elaine@woodapple.net','elainegreyling8@gmail.com',
  'elbie.conr@gmail.com','elize.breytenbach@mediclinic.co.za','elize.combrinck@gmail.com',
  'elizea@vodamail.co.za','elizebruyns28@gmail.com','elizedoig@gmail.com',
  'elizekleyn@gmail.com','elizemeintjes.cej@gmail.com','elizepienaar1952@gmail.com',
  'elizevdwalt75@gmail.com','elizma.bester89@gmail.com','elizmazeelie47@gmail.com',
  'elmare5319@gmail.com','elmarie.warren@zutari.com','elmarie@louwheyl.co.za',
  'elmarievanzyl1@gmail.com','elmarievg@gmail.com','elmaryn@prma.co.za',
  'elnihelm@gmail.com','eloisematthee@gmail.com','elona.loots1977@gmail.com',
  'elsana1969@gmail.com','elsie.slaterkinghorn@gmail.com','elsiee780@gmail.com',
  'elzaanberrange@gmail.com','elzabemarais@gmail.com','elzette.cantarello@gmail.com',
  'elzoniacloete@gmail.com','emhammond67@gmail.com','emil@defendsa.co.za',
  'endrieni@gmail.com','engela.blom@gmail.com','engeladuplooy@gmail.com',
  'erikaswart1@gmail.com','ermelo@ujoint.co.za','ermi.joubert@gmail.com',
  'erna.redinger@gmail.com','ervirtualbiz@gmail.com','esme@sarto.co.za',
  'esmeborruso@yahoo.com','esna.mostert@gmail.com','este.duvenage@gmail.com',
  'estellesayer@gmail.com','esterfbellaf@gmail.com','esterhuizen.annalie@gmail.com',
  'esther.kruger@farmovs.com','estherconradie@gmail.com','etolman0@gmail.com',
  'eva.huysamen@gmail.com','ezmari.nel@gmail.com','ferreira.henning007@gmail.com',
  'ferreira.ronalda@gmail.com','flewies20@gmail.com','florencedaffue@gmail.com',
  'fouriebelinda@gmail.com','fourienellie7@gmail.com','francisjsmit1@gmail.com',
  'fransdup77@gmail.com','frieda.cilliers@gmail.com','friedacilliers@gmail.com',
  'friedaloots@gmail.com','frvonwielligh@gmail.com','fstmotors@mail.com',
  'gbekker@mweb.co.za','gd.haasbroek@hotmail.com','gemery78@gmail.com',
  'geneenroos@yahoo.com','george@gttyreservices.co.za','gerdabotha22@gmail.com',
  'gerdamalan99@gmail.com','gerrielourens.gl@gmail.com','gertha.resca@gmail.com',
  'ghostpepfarm@gmail.com','gideon@klerksdorpengineering.co.za','gideonbr65@gmail.com',
  'gisellevisser@outlook.com','glenliebenberg@gmail.com','granetcouriers@gmail.com',
  'greeff.ac@gmail.com','greta@gbacc.co.za','grietjie.naude@gmail.com',
  'grimeshestie@hotmail.com','groblerdorette@gmail.com','gutters4life@gmail.com',
  'haasbroekyolanda@gmail.com','hanliebrits@hotmail.co.uk','hannelie@psprok.co.za',
  'hanneliendas@gmail.com','hannerievisser@gmail.com','hanniebritz611@gmail.com',
  'hartprop@mweb.co.za','heindre.koster@gmail.com','heinrich@infinityinc.co.za',
  'heksie1971@gmail.com','helenjj76@gmail.com','helga.welgemoed.smith@gmail.com',
  'hellodolly.haarkapper@gmail.com','helpmyvoort@gmail.com','hendrienbot1@gmail.com',
  'hendrik.knoetze@vodamaip.co.za','hendrikszrolene@gmail.com',
  'hendrineconradiedevos@gmail.com','herbstarline6@gmail.com','herfer1111@gmail.com',
  'herman.rina@yahoo.com','hermanusjoubert@gmail.com','hermie.lauwrens@gmail.com',
  'hermienboshoff@yahoo.com','hermienie@gmail.com','hester@tholosteel.com',
  'hesterric@gmail.com','heymansriana6@gmail.com','hilda@marula24.co.za',
  'hilton.annalize@gmail.com','hjventer11@gmail.com','hmpotgieter@gmail.com',
  'hoffmanlena218@gmail.com','hoffmanlena218@gmaill.com','hp32995@gmail.com',
  'hvangreunen@gmail.com','ida.krugel@gmail.com','idaspang@gmail.com',
  'idofosters@gmail.com','ijbata@gmail.com','info@groenrivier.co.za',
  'info@reserveresidence.co.za','ingesfick@gmail.com','irmari@live.co.za',
  'ishelle77@gmail.com','itcats@gmail.com','izelrimarx@gmail.com',
  'j.joubert.72@gmail.com','j.vanaswegen@telkomsa.net','jackie.s.erasmus1@gmail.com',
  'jaco@3phaseelectrical.co.za','jacolinebeukes8@gmail.com','jacques.maritz35@gmail.com',
  'jacquesmalanpotgieter@gmail.com','jamica1@vodamail.co.za','jana@mmmm.co.za',
  'janetstander76@gmail.com','janhermanlategan@yahoo.com','janine.grobler100@outlook.com',
  'janine72072@gmail.com','janinerudolph1967@gmail.com','jansevanrensburghettie@gmail.com',
  'japiebyleveldt@gmail.com','jaqulienod@gmail.com','jcckruger@gmail.com',
  'jcpretorius59@gmail.com','jeanette.biggs@gmail.com','jeanette.engelbrecht@gmail.com',
  'jeanette.swart@gmail.com','jeanettebeukman@gmail.com','jenice@mweb.co.za',
  'jenny_duplessis@hotmail.com','jhnel1963@gmail.com','jianri123@gmail.com',
  'jjacobs@wrcs.co.za','jjedoherty@gmail.com','jkluever@gmail.com',
  'jlsventerboerdery@gmail.com','jlwolhuter@gmail.com','jmjonker007@gmail.com',
  'joangauche49@gmail.com','joeydelport1973@gmail.com','joeydv@remaxdazzle.co.za',
  'johan.hboucher@gmail.com','johancape@gmail.com','johanestel@gmail.com',
  'johanevanrooyen.jvr@gmail.com','johann.olivier.faith@gmail.com',
  'johannamuller0@gmail.com','johlenekhunou8@gmail.com','jpkoekemoer55@outlook.com',
  'jpllab@gmail.com','judith.erasmus@yahoo.com','judithvanrooyen16@gmail.com',
  'judyvanbergen@yahoo.com','jullienvanvuuren@gmail.com','jurie70@gmail.com',
  'juringanaris@gmail.com','juzelle@mweb.co.za','jvorster0306@icloud.com',
  'kabbouter@yahoo.com','kandas03@gmail.com','kannakougoed@gmail.com',
  'karen@lynlaw.co.za','karenjanssen70@gmail.com','karenvt07@gmail.com',
  'karienbekker02@gmail.com','karinposthumus40@gmail.com','kiewietbruwer4@gmail.com',
  'kilianciska@gmail.com','klossiecollen@gmail.com','kolienel@gmail.com',
  'kotiedp@mweb.coza','kotiejvv17@gmail.com','kotiemossie@gmail.com',
  'krieltalita0@gmail.com','kroonboeke@lantic.net','kruger.sandra.d@gmail.com',
  'krugerelzanne@gmail.com','kventer01@gmail.com','ladyhawlk77@gmail.com',
  'lanielewis.com@gmail.com','larodee@gmail.com','leabritz@gmail.com',
  'leander.botha@gmail.com','leatitia.melville05@gmail.com',
  'leeann.watkins@premierfmcg.com','lehanejacobs@gmail.com','leonavanrooyen4@gmail.com',
  'leonie@barbourthorne.co.za','leoniebam1@gmail.com','leonieserasmus@gmail.com',
  'leonterblanche76@gmail.com','lerizegrabe@gmail.com','lerouxdalene@gmail.com',
  'leshanahenning@gmail.com','leticiavanwyk81@gmail.com','letitia.hbsn@gmail.com',
  'lewouns@gmail.com','lia.pauley@gmail.com','liebduraan47@gmail.com',
  'liefiedejager@yahoo.com','liezelvanwyk33@gmail.com','liezlmalan6@gmail.com',
  'linda.vans7060@gmail.com','linda.zeelie26@gmail.com','lindaford123@yahoo.com',
  'lindavanhuys@gmail.com','lindemalinda@gmail.com','lizanv@nashuaisp.co.za',
  'lizelle.beyers@yahoo.com','lizette@dpfsa.co.za','llepart@gmail.com',
  'lloydgrobler81@gmail.com','loodmuller1963@gmail.com','lorainefinlayson@gmail.com',
  'louibez@gmail.com','louisakidson2@gmail.com','louisevh@lantic.net',
  'louwmariette6@gmail.com','louwnicolene7@gmail.com','lpienaar1990@gmail.com',
  'lydia.stroebel.ls@gmail.com','lyla31_@hotmail.com','m.bodington62@gmail.com',
  'mabotha79@gmail.com','mabuabookings@gmail.com','magdadl6171@gmail.com',
  'magdaleen87@gmail.com','magdamuller6511@gmail.com','magrietajacobs70@gmail.com',
  'mail4rozelle@gmail.com','makahema2@gmail.com','malcolm@wenzane.co.za',
  'manda.cam3@gmail.com','mandieroos7002@gmail.com','manhattan2607@gmail.com',
  'maraispatat@gmail.com','maramyburgh7@gmail.com','marantelec@gmail.com',
  'marcelvdb31@yahoo.com','mareikapieterse@gmail.com','marelise.westfall@gmail.com',
  'marelismit50@gmail.com','marelize.dewaal@gmail.com','marelizeroets1103@gmail.com',
  'maresavisser4@gmail.com','marethalc123@gmail.com','margaretfourie7@gmail.com',
  'mariaan.duplessis3@gmail.com','mariafourie3@gmail.com','marianevdmerwe123@gmail.com',
  'marianmia6@gmail.com','mariavanrooyen946@yahoo.co.za','marie.coertzen@outlook.com',
  'marie4vv@gmail.com','mariesevdlinde@gmail.com','mariesteyn4@gmail.com',
  'marietha@homekeys.co.za','mariethadejager46@gmail.com','marietjie55avon@gmail.com',
  'mariette3@gmail.com','mariettejvv1@gmail.com','mariettematthee2106@gmail.com',
  'mariewright736@gmail.com','marileroux@mweb.co.za','marilizepretorius2@gmail.com',
  'marina.scholtz@gmail.com','marinag1711@gmail.com','marindapieterse@yahoo.com',
  'mariska.venter@gmail.com','mariskadw@gmail.com','maritzadejager1@gmail.com',
  'mariusminnie3@gmail.com','mariza@lucidum.co.za','marlene.brink60@gmail.com',
  'marlenem.theart@gmail.com','marlenesedutrading0001@gmail.com',
  'marlise12pretorius@gmail.com','marlizedp@gmail.com','marte.brummer@gmail.com',
  'marthiepienaar@icloud.com','martie.dannhaueser2@bakerhughes.com',
  'martiej.engelbrecht@gmail.com','martin@mmlotz.co.za','martistander14@gmail.com',
  'maruschkapitzer@gmail.com','marykasmit1114@gmail.com','marykebredenkamp768@gmail.com',
  'marykeheunis@yahoo.com','marykek@multiconnamibia.com','marykekruger123@gmail.com',
  'marynadlj@gmail.com','marynamatthysen@gmail.com','marynaviljoen@gmail.com',
  'matildadercksen60@gmail.com','mdasilva300673@gmail.com','mdesousa531@gmail.com',
  'mdt5200@gmail.com','meintjiesamanda048@gmail.com','meisiep01@gmail.com',
  'melismostert12@gmail.com','metalcraftpe@gmail.com','mf.schlierkamp@gmail.com',
  'mferreira782@gmail.com','mftgarden@gmail.com','mg.venter@gmail.com',
  'michel@mebisa.co.za','michelledunn291@yahoo.com','michellevdyk1@gmail.com',
  'micvdw@gmail.com','miemie.jomies@gmail.com','miemie5111@gmail.com',
  'mikkie44@gmail.com','minky.za@gmail.com','mlouw25@gmail.com',
  'mmoppermanmo@gmail.com','moiradebruin@gmail.com','monicadupreez289@gmail.com',
  'monicakabouter55@gmail.com','moreen@internext.co.za','mouton.duifies@gmail.com',
  'mpret75@gmail.com','msrita.trollip@icloud.com','muller.elmarie@yahoo.com',
  'muruimvanrensburg@yahoo.com','mvandriel93@gmail.com','mvanstraaten@live.com',
  'mvdberg@man-jhb.co.za','mw.vandeventer@gmail.com','myrtlezwarts@gmail.com',
  'mzs@mweb.co.za','nadenewickens@gmail.com','nadiaweddings@gmail.com',
  'nadine.dubruyn@icloud.com','namibie45@gmail.com','nanette.boucher15@gmail.com',
  'nans@lcproofing.co.za','natachadelange55@gmail.com','natalie@nkewutransport.co.za',
  'natasha.duplessis558@gmail.com','natashackmail@gmail.com','natlessing@gmail.com',
  'naude.debbie@gmail.com','naudemartha606@gmail.com','naudeteich@gmail.com',
  'neliavanstaden88@gmail.com','nellaverwey@gmail.com','nelliereynecke@yahoo.com',
  'nelma@remax-townandcountry.co.zaa','nicaljlom@gmail.com','nicolene.kriel82@gmail.com',
  'nicoletted@hotmail.co.za','nicolettem86@gmail.com','niekerkkotie@gmail.com',
  'nielrobbert@gmail.com','nitagrobler10@gmail.com','njordaan51@gmail.com',
  'nooiwilken@gmail.com','northam@jch.co.za','office@all3.co.za',
  'oosthuizen.emmarentia@gmail.com','orders@southgatelodge.co.za',
  'packnspicebrits@gmail.com','passersolution@gmail.com','pastteddy66@gmail.com',
  'patrickjasson14@gmail.com','pauline@efw.co.za','peetzestelle@gmail.com',
  'petro.propcor@gmail.com','petrolouw8@gmail.com','petroolckers70@gmail.com',
  'phendriks436@gmail.com','piet.warnick@gmail.com','pietbotha2821@gmail.com',
  'pietersenjelwine@gmail.com','pjdupreez38@gmail.com','pkrogh@mweb.co.za',
  'plk.manager@acdcexpress.com','precision@jenny.co.za','pretmaryna40@gmail.com',
  'pretoriusbianka1@gmail.com','pretoriusem@gmail.com','printware@hotmail.co.za',
  'purpleworx@gmail.com','pvorster4444@gmail.com','raasblaarr@gmail.com',
  'rachellewarne@hotmail.co.za','readlorenzo@gmail.com','rene@bsport.co.za',
  'rene@onze-rust.co.za','rene@perfscreens.co.za','renthiabester@gmail.com',
  'retha1330@gmail.com','riana.roos408@gmail.com','rianajacobs7@gmail.com',
  'riasteenkamp249@gmail.com','riekietiek@gmail.com','rika.swanepoel@gmail.com',
  'rikavanr@gmail.com','rina.richards57@gmail.com','rinadurand8@gmail.com',
  'rinagrobler@gmail.com','riqnel67@gmail.com','rizemarxpelser@gmail.com',
  'robbiegrobler96@gmail.com','rohan.herbst@gmail.com','ronelbleeker1033@gmail.com',
  'roneldupreez813@gmail.com','ronelkuhn2@gmail.com','ronelrossouw@yahoo.com',
  'rosie.zeelie@gmail.com','roxane.keeve@gmail.com','rozalnavh@gmail.com',
  'rudolphp246@gmail.com','rykheermal007@gmail.com','rykieerasmus76@gmail.com',
  'rynohm87@gmail.com','rynokannemeyer@gmail.com','s.kleyn@yahoo.com',
  'salomiesteyn@gmail.com','sam@smtadmin.co.za','sannandale14@gmail.com',
  'santie.meyer25@gmail.com','sarelrei@telkomsa.net','sarelv@mweb.co.za',
  'sarienavanzyl@gmail.com','sarina.mellet7@gmail.com','sashaduplessis95@gmail.com',
  'sasnowske@gmail.com','satworld@vodamail.co.za','schanaishuman@gmail.com',
  'scheeperscupido@gmail.com','schreudermerilyn@gmail.com',
  'schubert.theunette1@gmail.com','schuttetanja@gmail.com',
  'sharenvanrensburg@gmail.com','shatsie@icloud.com','silviagideon@gmail.com',
  'sim1dicks@gmail.com','skewies.erika@gmail.com','slaterpetro@gmail.com',
  'smillar007@yahoo.ca','smithalwyn6@gmail.com','smithvernon77@gmail.com',
  'snagel2911@gmail.com','solly.vandermerwe@videojet.com',
  'somersetguesthouse@hotmsil.com','sonikasmith37@gmail.com','sonjabothma0@gmail.com',
  'sonjadegoede1968@gmail.com','sonjasteynharmse@gmail.com','sonsmulder@gmail.com',
  'sophialucia8400@gmail.com','soretavstraaten@gmail.com','spooksmith00@gmail.com',
  'srichteraos@gmail.com','stefaansolivier@hotmail.com','steph@plassil.co.za',
  'stephancarstens@hotmail.com','stephlines92@gmail.com','stienievanwyk9@gmail.com',
  'stoltzbertus@gmail.com','stompiesmr@gmail.com','suelourens6@gmail.com',
  'sugenen@gmail.com','sunee9000@gmail.com','sunel.lingenfelder1@gmail.com',
  'sunetb@za.neolife.com','superstokkie1@gmail.com','sureyneethling2@gmail.com',
  'susanduplooy.SDP@gmail.com','susanevn44@gmail.com','susanvanniekerk34@gmail.com',
  'susette.botha69@gmail.com','sventer@mail.com','swiegersannelize@gmail.com',
  'sylviamswart@gmail.com','taljard.tian@gmail.com','tanjajvvuuren@gmail.com',
  'tanjaneethling@yahoo.com','tanyabotha@eject.co.za','tanyaredelinghuys@gmail.com',
  'tanzi.jacobs@gmail.com','taylor.ronassv@gmail.com','tckoen@gmail.com',
  'telanie78@gmail.com','terencecowley.tc@gmail.com','tererasmus@gmail.com',
  'tersiamuller@yahoo.com','thariaroos@icloud.com','theamullerjp@gmail.com',
  'theasteyn74@gmail.com','theunissenmarelize27@gmail.com','thinus.beylefeld@gmail.com',
  'thompsonanita@hotmail.com','tina.nel0227@gmail.com','tjok.brand@gmail.com',
  'toetsiew@gmail.com','tosh.odendaal@outlook.com','traceerwee@gmail.com',
  'tracyg@tru-cape.co.za','troos333@gmail.com','ulindimouton@gmail.com',
  'v.neveling@gmail.com','vanderlindesusan@gmail.com','vandermerwecoba@gmail.com',
  'vanderrystmadri@gmail.com','vanheerdenm78@icloud.com','vanniekerkelize2@gmail.com',
  'vanniekerkina07@gmail.com','vanrensburgtessa@gmail.com',
  'vanrooyen.marietjie2@gmail.com','vanwykdanie04@gmail.com','veerpg@gmail.com',
  'venessaw777@gmail.com','venjen85@gmail.com','ventertaina@gmail.com',
  'venteryolande75@gmail.com','veronica.reis@betterbond.co.za',
  'versteryolandi391@gmail.com','vickycilliers75@gmail.com','vil2babysteps@yahoo.com',
  'vilcorda@gmail.com','viljoenam83@gmail.com','viljoenl5@gmail.com',
  'viljoennandi@gmail.com','vlooi.jm@gmail.com','vrystaat.danielle@gmail.com',
  'wallisleonie@yahoo.com','waynecombrink23@gmail.com','welverdiend@vodamail.co.za',
  'welverdiendstud@gmail.com','wendycrd@gmail.com','wesselleroux009@gmail.com',
  'whatsnewmari@gmail.com','wilmacalitz67@gmail.com','wilnawilhelmina@gmail.com',
  'wminie@sars.gov.za','ybrits@gmail.com','ycvanniekerk@gmail.com',
  'yolanda.badenhorst1@outlook.com','yolandavzyl@gmail.com','yolandedutoit@icloud.com',
  'yolandeoosthuyzen1@gmail.com','yolandiecilliers222@gmail.com',
  'yolandimarais89@gmail.com','zelda.human@icloud.com','zeldabraack99@gmail.com',
  'zeldadirk@gmail.com','zelnaoberem@gmail.com','zenithms@mweb.co.za',
  'zerene.lag@gmail.com','zirkiag06@gmail.com','ztlewies@gmail.com',
]

async function getAccessToken() {
  const now    = Math.floor(Date.now() / 1000)
  const header = Buffer.from(JSON.stringify({ alg: 'RS256', typ: 'JWT' })).toString('base64url')
  const claim  = Buffer.from(JSON.stringify({
    iss: process.env.FIREBASE_CLIENT_EMAIL,
    scope: 'https://www.googleapis.com/auth/datastore',
    aud: 'https://oauth2.googleapis.com/token',
    iat: now, exp: now + 3600,
  })).toString('base64url')
  const privateKey = (process.env.FIREBASE_PRIVATE_KEY || '').replace(/\\n/g, '\n')
  const sign = crypto.createSign('RSA-SHA256')
  sign.update(`${header}.${claim}`)
  const sig = sign.sign(privateKey, 'base64url')
  const jwt = `${header}.${claim}.${sig}`
  const r = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: `grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${jwt}`,
  })
  const data = await r.json()
  if (!data.access_token) throw new Error('No token: ' + JSON.stringify(data))
  return data.access_token
}

async function fsWrite(projectId, token, path, fields) {
  try {
    await fetch(
      `https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents/${path}`,
      {
        method: 'PATCH',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ fields }),
      }
    )
  } catch {}
}

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).send('Not Allowed')
  const { pin } = req.body || {}
  if (pin !== '2025') return res.status(403).send('Forbidden')

  const projectId = process.env.FIREBASE_PROJECT_ID || 'daaglikse-hoop'
  let token
  try { token = await getAccessToken() } catch (e) {
    return res.status(500).json({ error: 'Auth misluk: ' + e.message })
  }

  const unique = [...new Set(INITIAL_EMAILS.map(e => e.toLowerCase().trim()).filter(Boolean))]

  const chunks = []
  for (let i = 0; i < unique.length; i += 50) chunks.push(unique.slice(i, i + 50))

  let count = 0
  for (const chunk of chunks) {
    await Promise.all(chunk.map(async email => {
      const id = Buffer.from(email).toString('base64').replace(/[^a-zA-Z0-9]/g, '_')
      await fsWrite(projectId, token, `emailList/${id}`, {
        email:   { stringValue: email },
        source:  { stringValue: 'import' },
        addedAt: { timestampValue: new Date().toISOString() },
      })
      count++
    }))
  }

  return res.json({ ok: true, imported: count })
}
